### PR TITLE
Add Dockerfile support

### PR DESCRIPTION
**Pull request by rtfpessoa**
I read some other PR and tried to write support for Dockerfile.

I could not find any docs on how to contribute.

I did the file `Dockerfile.yaml` by hand, but it looks generated. How do I get it?

Do I need something else? Can you help me?

### CODE REVIEW

**Comment by AlDanial** [comment]
Looks good as-is; `Dockerfile.yaml` should be created by cloc itself with the `--yaml` switch.

**Comment by rtfpessoa** [comment]
I am not sure this is working correctly yet.

I tried compiling this with: `make prefix=/tmp install`

and then

`/tmp/bin/cloc tests/inputs/Dockerfile`

and I get

```
       1 text file.
       1 unique file.
       1 file ignored.
```

What am I doing wrong?

**Comment by AlDanial** [comment]
Works for me:
<pre>
> cloc tests/inputs/Dockerfile 
       1 text file.
       1 unique file.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.71  T=0.01 s (189.4 files/s, 10982.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Dockerfile                       1              4              1             53
-------------------------------------------------------------------------------
</pre>

**Comment by rtfpessoa** [comment]
Weird, ok.

Do you plan on doing a release soon?

**Comment by AlDanial** [comment]
Released 1.72 today.

**Comment by rtfpessoa** [comment]
@AlDanial thank you.

**Pull request merged**
