### PR TITLE
dont traverse into folders in order to support long paths under windows

### PR DESCRIPTION
**Pull request by x29a**
This fixed issue #58 for me

### CODE REVIEW

**Comment by AlDanial** [comment]
Thanks for providing the patch.  There are a few places in cloc where the cwd matters so over the next few days I'll test those branches to see how they are affected by the no_chdir setting.

**Comment by AlDanial** [comment]
Just a quick heads-up:  the patch breaks the --match-d switch, the first one I tested.  There are other directory related options (--not-match-d, --exclude-dir, --fullpath) that are likely affected too.

Given the dozen or so references of cwd and chdir commands in the code, it will take a non-trivial refactoring effort to use <code>no_chdir => 1</code>.  So it will be on the long term, rather than short term, schedule.

**Comment by x29a** [comment]
Thanks for looking into this. I can live with the "local" patch for now. Do you have a testsuite to test cloc against or was this just some manual finding?

**Comment by AlDanial** [comment]
My testsuite is in a terrible shape; I found this problem manually.  My first order of business is get my tests in healthy order again, that will give me much more confidence when refactoring the code to work with your patch.

**Comment by AlDanial** [comment]
Regretfully I don't see a path to merge the code in without a substantial re-write to support the other directory filters.

**Pull request closed without merging**
