### PR TITLE
added a batch file for windows users

### PR DESCRIPTION
**Pull request by waynenilsen**
this is a very simple batch file but I found it useful after installing strawberry perl. this is now how I am using cloc

### CODE REVIEW

**Comment by waynenilsen** [comment]
I also added the git `cloc` directory to the path that way it works how I want (eg `cloc .` does what i want it to do.)

**Comment by AlDanial** [comment]
hi, can you tell me what cloc.bat provides for Windows users?  I'm not familiar enough with bat files to understand the "%~dp0\" part.

**Comment by waynenilsen** [comment]
Just read `%~dp0` as the directory that this batch file is in. `%*` just means pass all of the arguments to this batch file along to here. Essentially this is so that, if I add the cloned git repo to my path, I can use cloc by typing `cloc ...` so long as I have a perl interpreter installed. I can update the readme to this effect as well

**Comment by AlDanial** [comment]
I added your .bat file but have two requests:  yes, please add some lines to the readme, and also add a couple of REM comments to the .bat file explaining what it does (and add your name as its author too!).

**Pull request closed without merging**
