### PR TITLE
Add Extensions for Support Languages from Linguist

### PR DESCRIPTION
**Pull request by asadcr**
Source : https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

### CODE REVIEW

**Comment by AlDanial** [comment]
Looks good except for the inclusion of three definitions which already exist:
<pre>
'escript'  => 'Erlang'
'rakefile'  => 'Ruby'
'ruby'     => 'Ruby'
</pre>
Please remove these from the PR and I'll merge.

**Comment by asadcr** [comment]
@AlDanial Good Point. Removed.

**Comment by asadcr** [comment]
@AlDanial Are we planning a release ?

**Comment by AlDanial** [comment]
Yes: September 2019

**Pull request merged**
