### PR TITLE
Add support for AnsProlog (Answer Set Programming)

### PR DESCRIPTION
**Pull request by tgamblin**
[Answer Set Programming](https://en.wikipedia.org/wiki/Answer_set_programming) (ASP) is a declarative programming paradigm oriented towards combinatorial search problems. Most ASP solvers (notably, [clingo](/potassco/clingo)) accept a language called AnsProlog ("Answer Set Programming in Logic"), which is enough like Prolog for its lines to be counted the same way, but it typically uses the `.lp` ("logic program") suffix.

ASP is different enough from Prolog that it deserves to be reported separately -- this patch will cause ASP code to be reported as AnsProlog, while regular Prolog programs will be reported as Prolog, so you can tell them apart if they're in the same repository.

- [x] Add filters for AnsProlog
- [x] Add `.lp` suffix for AnsProlog
- [x] Add scale factor for AnsProlog
- [x] Update `README.md`

### CODE REVIEW

**Comment by tgamblin** [comment]
@rkaminsk FYI

**Comment by rkaminsk** [comment]
> @rkaminsk FYI

Just had a quick look. In the clingo language, single line comments are started with `%` and block comments enclosed in `%*` and `*%`. Most files should use Prolog's single line comments, however.

**Comment by tgamblin** [comment]
Ok I've gone ahead and added `%*` / `*%` comments and removed the call to common C regexes... which doesn't seem to change much.  I'm assuming clingo doesn't do `/*` and `*/` like prolog anyway, right?

**Comment by rkaminsk** [comment]
> Ok I've gone ahead and added `%*` / `*%` comments and removed the call to common C regexes... which doesn't seem to change much. I'm assuming clingo (and AnsProlog) doesn't support `/*` and `*/` like prolog anyway, right?

I think it is fine now. `/*` is not used to indicate comments and could only appear in quoted strings.

**Comment by AlDanial** [comment]
Can you also post a small `.lp` file demonstrating the various comment methods?  I'll add it to the unit tests.

**Comment by tgamblin** [comment]
@AlDanial I added `test.lp` to the test inputs directory -- it has some sample code and comments describing the expected counts. Let me know if this is good.

**Comment by AlDanial** [comment]
Looks good, thanks.

**Comment by tgamblin** [comment]
Thanks!

**Pull request merged**
