### PR TITLE
added to readme; perform Cloc functionality on subLevel of a directory

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
If you need any clarification for this contribution I can be reached at email.
MichaelDimmitt@icloud.com
a more in depth description/ example can be found here:
https://github.com/MichaelDimmitt/Bash_Directory_CLOC-Count-Lines-of-Program

program will work appropriately if too much nesting is performed.
However, will miss submost levels if nesting does not exist to reach that level.
each time you nest the command, you access a level deeper into a directory.

This command that I am adding was very useful when I was evaluating a large number of projects on github.
I would put them in a repository. Clone the repository down. And run the allSubdir's command to quickly see how large the different programs were before looking at any of the code.

nice overall program, cheers! Michael Dimmitt

### CODE REVIEW

**Comment by MichaelDimmitt** [comment]
The command added to Readme was run using git Bash on windows.

**Comment by AlDanial** [comment]
Just to be clear that I understand the process you're documenting:  you're showing a way to invoke cloc to count lines of code in files that exist only in one directory (as opposed to recursively descending the directory as cloc would do by default), then repeating this process over a directory tree?  I get the sense that your motivation is working with a large number of cloned repos and you're looking to count the code in each repo?

Wouldn't you also want to insert a command to echo the name of the directory cloc is producing output for?  Without that there's no context for the breakdown of counts by language.

Or maybe I don't fully understand the objective.

**Comment by MichaelDimmitt** [comment]
I was unaware that cloc went recursively through all subfolders.
with this new information, the command does not need to be embedded.

To clarify, yes, I found it useful to put many projects into a folder. 
then, get the lines of code for each project before I made a decision on what project to pursue. 

running the command 
for d in ./*/ ; do (cd "$d" && cloc $(git ls-files)); done
allows an analysis of all subfolders. 
 
I checked on my mac today, which is using cloc installed via homebrew.
and it correctly showed the comparison I found useful.

since I have moved away from embedding should I make a new pull request to clarify?
or change the pull request?
Do you find this command/information useful?

let me know if you need anything else.

**Comment by AlDanial** [comment]
Yes, please submit a PR that is consistent with cloc's native (ie recursive) behavior.  Also, while you're at it you can also look at the docs for the `--vcs` option which gives better results for git (via `--vcs git`) and subversion (via `--vcs svn`) options.  You may want to roll those into your script.

**Pull request merged**
