### PR TITLE
support large file sets with --git --diff

### PR DESCRIPTION
**Pull request by hawkli-1994**
I improved this tool to support comparison of large files.

### CODE REVIEW

**Comment by AlDanial** [comment]
Can you point me to a repo that has files large enough to demonstrate the utility of your code?  So far I haven't had difficulties with ``--git --diff``.  Perhaps my files aren't big enough to be problematic.

**Comment by hawkli-1994** [comment]
My project is a project with 120,000 lines of code. When I try to diff the first commit and the last commit, it has an error like "argument list too long". So I made this change. Since the project belongs to the company, I can't provide you with the test, but I think this problem should occur with a project that is big enough.

**Comment by AlDanial** [comment]
OK I know what you're talking about now.  This problem was first reported in February and I've since fixed it on the development branch, please see #273.  Try running with the latest code (https://raw.githubusercontent.com/AlDanial/cloc/master/cloc) and see if you get results.  If not I'll dig into this further.

**Comment by hawkli-1994** [comment]
From result, cloc counted that all code was removed and, not counted additional,modified and same code.
It seems that diff algorithm is incorrect.And commit [6a8947b](https://github.com/AlDanial/cloc/commit/6a8947b590a721d828914c5f816f74d38aae2700) is not correct

**Comment by AlDanial** [comment]
I tried the following to see if the code in your PR produces different results from what the development version of cloc (these are the same commands from #273):
<pre>
cd /tmp
git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
cd linux-stable
git checkout v4.14.13
# Run 1 using cloc from the dev branch
cloc --diff 1da177e4 b8447222
# Run 2 using cloc updated with your PR (your commit 31e9bd930101):
../../PR/cloc/cloc --diff 1da177e4 b8447222
</pre>

Both runs yield the same result.  The summary block is
<pre>---------------------------------------------------------------------------------------
SUM:
 same                                    0              0         338862        1176680
 modified                             5550              0          50413         422913
 added                               44121        2732617        2931033       15269245
 removed                              9979         482660         647237        2709640
---------------------------------------------------------------------------------------
</pre>

Can you post commands that demonstrate that your PR generates different (and more correct) results than the baseline?

**Comment by hawkli-1994** [comment]
Thank you very much for your work. Since this submission has not been effectively improved, I will close it first. I will continue to pay attention to cloc.

**Comment by AlDanial** [comment]
Even though your PR was not merged, I'm grateful to you for the effort you took to try to improve the tool.  I look forward to future contributions.

**Pull request closed without merging**
