### PR TITLE
Fix typo of ssc to scc

### PR DESCRIPTION
**Pull request by boyter**
Single character typo.

### CODE REVIEW

**Comment by boyter** [comment]
Not sure how the CI check for this failed... something to do with what I took the branch from? Or a bug in it? I would have assumed a single character change to a markdown file would not break anything.

**Comment by AlDanial** [comment]
Hard to believe I can put a typo in a three letter name, sheesh.  I'll also need to reposition it in the list since the intent is to have the counters appear alphabetically.

Regarding AppVeyor, I need to disable that.  The intent was to have a Windows binary built and tested automatically but the setup for that is excessive.

**Comment by boyter** [comment]
Hah don't feel bad. I managed to do it a few times myself. I like the name but it can be easy to misspell till you are used to it.

Ill redo it now and submit another PR if you prefer. Save you the effort.

**Comment by boyter** [comment]
Oh you already did. As you were then!

**Pull request merged**
