### PR TITLE
Add triple extension support.

### PR DESCRIPTION
**Pull request by cansin**
I have a use case where we rely on double extensions to distinguish between different JS files, like: `something.ng.js` vs. `other-thing.jq.js`, and there are consecutive spec files for each file like `something.ng.spec.js` vs. `other-thing.jq.spec.js`. Not having triple extension support makes it harder for me to create custom language classes through `--read-lang-def`. I acknowledge that this is a seldom use case, but the changeset is small and should not affect existing functionality. Therefore I think it is reasonable. @AlDanial wdyt?

### CODE REVIEW

**Comment by AlDanial** [comment]
I'll have time to review this in about one week.

**Comment by AlDanial** [comment]
nice work, thank you

**Comment by cansin** [comment]
@AlDanial thanks! Do you have an idea when you'd release next version of cloc? Seems like it's been a while since last release (January 14, 2017).

**Comment by AlDanial** [comment]
It's relative, I suppose.  January 2017 is recent in my view.  My plan is for each year to have a summer release and a winter release.

**Comment by cansin** [comment]
Got it. Thanks for the reply!

**Pull request merged**
